/**
 * The ENICE Website Manager database schema.
 *
 * ## Why the SQL lives in TypeScript
 *
 * The serverless functions are bundled by esbuild into single files (`api-src/` → `api/`).
 * A `.sql` file sitting next to the source would not be included in that bundle and would not
 * exist at runtime on Vercel. Exporting the schema as a string means the migration ships with
 * the code that runs it, and there is no deploy step that can forget it.
 *
 * ## Design notes
 *
 * - **Ids are UUIDs generated by the application**, not by `gen_random_uuid()`. That keeps the
 *   schema free of the `pgcrypto` extension, so it applies unchanged on managed Postgres where
 *   `CREATE EXTENSION` may be refused, and it lets a handler know an id before the insert.
 *
 * - **`jsonb` for document-shaped fields** (`body`, `seo`, `sections`, `fields`, `metadata`).
 *   These are validated in application code by `src/lib/cms/doc.ts` and friends before they are
 *   written, and they are read back whole. Normalising a block document into rows would buy
 *   nothing and make every read a join.
 *
 * - **Denormalised `*_by_email` columns** sit alongside the `*_by` foreign keys. The key is
 *   `ON DELETE SET NULL`, so removing an administrator would otherwise erase the authorship of
 *   everything they ever touched. The email is captured at write time and kept as a historical
 *   record — which is also what makes the audit log trustworthy.
 *
 * - **Every statement is `IF NOT EXISTS`** and every migration is idempotent, because several
 *   serverless instances can cold-start at once and all try to migrate.
 */

/**
 * Ordered migrations. Append only — never edit or renumber an entry that has shipped, because
 * `cms_migrations` records which ids have run and a changed body will not be re-applied.
 */
export interface Migration {
  id: number;
  name: string;
  sql: string;
}

export const MIGRATIONS: Migration[] = [
  {
    id: 1,
    name: "initial_schema",
    sql: /* sql */ `
-- ─── Administrators ─────────────────────────────────────────────────────────
-- Email is stored lower-cased by the application; the UNIQUE constraint then gives
-- case-insensitive uniqueness without depending on the citext extension.
CREATE TABLE IF NOT EXISTS admin_users (
  id                    uuid PRIMARY KEY,
  email                 text NOT NULL UNIQUE,
  name                  text NOT NULL DEFAULT '',
  title                 text NOT NULL DEFAULT '',
  avatar_url            text,
  role                  text NOT NULL DEFAULT 'editor',
  -- active | invited | suspended
  status                text NOT NULL DEFAULT 'invited',

  -- NULL until an invited administrator sets a password.
  password_hash         text,
  password_updated_at   timestamptz,
  must_change_password  boolean NOT NULL DEFAULT false,

  -- TOTP secret, encrypted at rest (see api-src/lib/crypto.ts). Never returned by the API.
  totp_secret           text,
  totp_enabled          boolean NOT NULL DEFAULT false,
  totp_confirmed_at     timestamptz,
  -- Hashed single-use recovery codes: [{ "hash": "...", "usedAt": null }]
  recovery_codes        jsonb NOT NULL DEFAULT '[]'::jsonb,

  invite_token_hash     text,
  invite_expires_at     timestamptz,

  -- Brute-force state. Persisted rather than held in memory because each serverless
  -- instance has its own memory, so an in-process counter is trivially bypassed by
  -- spreading attempts across concurrent invocations.
  failed_attempts       integer NOT NULL DEFAULT 0,
  locked_until          timestamptz,

  last_login_at         timestamptz,
  last_login_ip         text,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS admin_users_role_idx ON admin_users (role);
CREATE INDEX IF NOT EXISTS admin_users_status_idx ON admin_users (status);

-- ─── Sessions ───────────────────────────────────────────────────────────────
-- Only the SHA-256 of the session token is stored. A database leak therefore does not
-- hand over usable sessions, exactly as with password hashes.
CREATE TABLE IF NOT EXISTS admin_sessions (
  id             uuid PRIMARY KEY,
  user_id        uuid NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
  token_hash     text NOT NULL UNIQUE,
  ip_address     text,
  user_agent     text,
  -- False between password verification and the TOTP step, so a half-authenticated
  -- session cannot reach any content route.
  mfa_satisfied  boolean NOT NULL DEFAULT false,
  created_at     timestamptz NOT NULL DEFAULT now(),
  last_seen_at   timestamptz NOT NULL DEFAULT now(),
  expires_at     timestamptz NOT NULL,
  revoked_at     timestamptz
);

CREATE INDEX IF NOT EXISTS admin_sessions_user_idx ON admin_sessions (user_id);
CREATE INDEX IF NOT EXISTS admin_sessions_expiry_idx ON admin_sessions (expires_at);

-- ─── Persisted rate limiting ────────────────────────────────────────────────
-- A fixed-window counter shared by every instance. Used for login attempts and for
-- capping AI requests.
CREATE TABLE IF NOT EXISTS cms_rate_limits (
  key       text PRIMARY KEY,
  count     integer NOT NULL DEFAULT 0,
  reset_at  timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS cms_rate_limits_reset_idx ON cms_rate_limits (reset_at);

-- ─── Editorial content ──────────────────────────────────────────────────────
-- Blog posts, announcements, updates and news share this table. They differ in where
-- they surface and which extras they carry, not in how they are authored, scheduled,
-- previewed or audited — so one table means one publishing pipeline and one audit path.
CREATE TABLE IF NOT EXISTS content_items (
  id               uuid PRIMARY KEY,
  kind             text NOT NULL,
  status           text NOT NULL DEFAULT 'draft',
  title            text NOT NULL DEFAULT '',
  slug             text NOT NULL,
  excerpt          text NOT NULL DEFAULT '',
  body             jsonb NOT NULL DEFAULT '{"version":1,"blocks":[]}'::jsonb,
  cover_image_url  text,
  author           jsonb,
  category         text,
  tags             text[] NOT NULL DEFAULT '{}',
  seo              jsonb NOT NULL DEFAULT '{}'::jsonb,
  extras           jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- Derived on write so listings never have to parse a document to render a card.
  reading_minutes  integer NOT NULL DEFAULT 0,
  search_text      text NOT NULL DEFAULT '',

  published_at     timestamptz,
  scheduled_for    timestamptz,
  archived_at      timestamptz,

  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  created_by       uuid REFERENCES admin_users(id) ON DELETE SET NULL,
  updated_by       uuid REFERENCES admin_users(id) ON DELETE SET NULL,
  created_by_email text,
  updated_by_email text,
  revision         integer NOT NULL DEFAULT 1,

  -- Slugs are unique per kind, so a blog post and an announcement may share one.
  CONSTRAINT content_items_kind_slug_key UNIQUE (kind, slug)
);

CREATE INDEX IF NOT EXISTS content_items_feed_idx
  ON content_items (kind, status, published_at DESC);
CREATE INDEX IF NOT EXISTS content_items_status_idx ON content_items (status);
-- Partial index: the scheduler only ever asks for rows still waiting to go live.
CREATE INDEX IF NOT EXISTS content_items_due_idx
  ON content_items (scheduled_for)
  WHERE status = 'scheduled';
CREATE INDEX IF NOT EXISTS content_items_updated_idx ON content_items (updated_at DESC);
-- to_tsvector with a literal configuration is immutable, so it can be indexed directly.
-- 'english' is core Postgres; no extension required.
CREATE INDEX IF NOT EXISTS content_items_search_idx
  ON content_items USING gin (to_tsvector('english', search_text));

-- ─── Revisions ──────────────────────────────────────────────────────────────
-- A snapshot per save, which is what makes "revert this change" possible.
CREATE TABLE IF NOT EXISTS content_revisions (
  id               uuid PRIMARY KEY,
  content_id       uuid NOT NULL REFERENCES content_items(id) ON DELETE CASCADE,
  revision         integer NOT NULL,
  snapshot         jsonb NOT NULL,
  note             text NOT NULL DEFAULT '',
  created_at       timestamptz NOT NULL DEFAULT now(),
  created_by_email text,
  CONSTRAINT content_revisions_unique UNIQUE (content_id, revision)
);

CREATE INDEX IF NOT EXISTS content_revisions_lookup_idx
  ON content_revisions (content_id, revision DESC);

-- ─── Taxonomies ─────────────────────────────────────────────────────────────
-- Categories and tags are suggestions surfaced in the editor, not a constraint on
-- content_items. Adding one must never require a deploy.
CREATE TABLE IF NOT EXISTS content_taxonomies (
  id         uuid PRIMARY KEY,
  kind       text NOT NULL DEFAULT 'global',
  taxonomy   text NOT NULL,
  name       text NOT NULL,
  slug       text NOT NULL,
  usage_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT content_taxonomies_unique UNIQUE (kind, taxonomy, slug)
);

-- ─── Pages ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS cms_pages (
  id               uuid PRIMARY KEY,
  path             text NOT NULL UNIQUE,
  title            text NOT NULL DEFAULT '',
  summary          text NOT NULL DEFAULT '',
  status           text NOT NULL DEFAULT 'draft',
  -- Ordered PageSection[]: structured blocks from the design system, never free layout.
  sections         jsonb NOT NULL DEFAULT '[]'::jsonb,
  seo              jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- True for paths backed by a hand-built React route. Editable, but not deletable:
  -- removing the row would leave a route in the bundle pointing at nothing.
  system_route     boolean NOT NULL DEFAULT false,
  published_at     timestamptz,
  scheduled_for    timestamptz,
  archived_at      timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  updated_by_email text,
  revision         integer NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS cms_pages_status_idx ON cms_pages (status);

-- ─── Global website sections ────────────────────────────────────────────────
-- Sections belonging to the site rather than to one page: the homepage hero, the
-- partners strip, the FAQ. Addressed by a stable key that a React component looks up.
CREATE TABLE IF NOT EXISTS site_sections (
  key              text PRIMARY KEY,
  label            text NOT NULL,
  group_name       text NOT NULL DEFAULT 'General',
  type             text NOT NULL,
  visible          boolean NOT NULL DEFAULT true,
  status           text NOT NULL DEFAULT 'published',
  fields           jsonb NOT NULL DEFAULT '{}'::jsonb,
  sort_order       integer NOT NULL DEFAULT 0,
  updated_at       timestamptz NOT NULL DEFAULT now(),
  updated_by_email text,
  revision         integer NOT NULL DEFAULT 1
);

-- ─── Settings ───────────────────────────────────────────────────────────────
-- One row per settings document: 'design', 'header', 'footer', 'seo', 'general'.
CREATE TABLE IF NOT EXISTS site_settings (
  key              text PRIMARY KEY,
  value            jsonb NOT NULL,
  updated_at       timestamptz NOT NULL DEFAULT now(),
  updated_by_email text
);

-- ─── Media ──────────────────────────────────────────────────────────────────
-- Metadata only. Bytes live in S3-compatible object storage; storage_key is what a
-- delete acts on. Keeping large files out of Postgres keeps backups and reads sane.
CREATE TABLE IF NOT EXISTS media_assets (
  id                 uuid PRIMARY KEY,
  storage_key        text NOT NULL UNIQUE,
  url                text NOT NULL,
  filename           text NOT NULL,
  mime_type          text NOT NULL,
  size_bytes         bigint NOT NULL DEFAULT 0,
  width              integer,
  height             integer,
  alt                text NOT NULL DEFAULT '',
  folder             text NOT NULL DEFAULT '',
  uploaded_by_email  text,
  created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS media_assets_created_idx ON media_assets (created_at DESC);
CREATE INDEX IF NOT EXISTS media_assets_folder_idx ON media_assets (folder);
CREATE INDEX IF NOT EXISTS media_assets_search_idx
  ON media_assets USING gin (to_tsvector('english', filename || ' ' || alt));

-- ─── Activity log ───────────────────────────────────────────────────────────
-- Append-only. The API never exposes an update or delete for this table.
CREATE TABLE IF NOT EXISTS activity_log (
  id           uuid PRIMARY KEY,
  actor_id     uuid REFERENCES admin_users(id) ON DELETE SET NULL,
  actor_email  text,
  actor_name   text,
  action       text NOT NULL,
  entity_type  text,
  entity_id    text,
  entity_label text,
  outcome      text NOT NULL DEFAULT 'success',
  ip_address   text,
  metadata     jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS activity_log_recent_idx ON activity_log (created_at DESC);
CREATE INDEX IF NOT EXISTS activity_log_actor_idx ON activity_log (actor_email, created_at DESC);
CREATE INDEX IF NOT EXISTS activity_log_action_idx ON activity_log (action, created_at DESC);
CREATE INDEX IF NOT EXISTS activity_log_entity_idx ON activity_log (entity_type, entity_id);

-- ─── AI change requests ─────────────────────────────────────────────────────
-- The review pipeline for AI-assisted changes. 'content' requests apply to CMS data on
-- approval; 'code' requests become a pull request, so a human still merges.
CREATE TABLE IF NOT EXISTS ai_change_requests (
  id                 uuid PRIMARY KEY,
  prompt             text NOT NULL,
  kind               text NOT NULL DEFAULT 'content',
  status             text NOT NULL DEFAULT 'queued',
  summary            text NOT NULL DEFAULT '',
  plan               jsonb NOT NULL DEFAULT '[]'::jsonb,
  content_edits      jsonb NOT NULL DEFAULT '[]'::jsonb,
  code_edits         jsonb NOT NULL DEFAULT '[]'::jsonb,
  checks             jsonb NOT NULL DEFAULT '[]'::jsonb,
  preview_url        text,
  branch             text,
  pull_request_url   text,
  review_note        text,
  error_message      text,
  -- The prior state of everything a 'content' request touched, so an applied change
  -- can be rolled back after the fact.
  rollback_snapshot  jsonb,
  requested_by_email text,
  reviewed_by_email  text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ai_change_requests_status_idx
  ON ai_change_requests (status, created_at DESC);
CREATE INDEX IF NOT EXISTS ai_change_requests_recent_idx
  ON ai_change_requests (created_at DESC);
`,
  },
  {
    id: 2,
    name: "knowledge_base",
    sql: /* sql */ `
-- ─── AI assistant knowledge base ────────────────────────────────────────────
-- Curated facts the PUBLIC chatbot (api/chat) grounds its answers in, so the site owner
-- can teach the assistant without a code change to the static system prompt.
--
-- An entry is either a typed note or the text extracted from an uploaded PDF; 'source_kind'
-- records which. The bytes of a PDF live in object storage like any other media — only the
-- extracted text is stored here, because that is what retrieval needs.
--
-- Retrieval is native Postgres full-text search over 'search_text' (title + body), exactly as
-- content_items and media_assets already do. Deliberately NOT pgvector: that needs
-- CREATE EXTENSION, which managed Postgres may refuse, and would break the zero-extension
-- guarantee the rest of this schema keeps. 'english' is a core dictionary, no extension needed.
CREATE TABLE IF NOT EXISTS knowledge_entries (
  id                uuid PRIMARY KEY,
  title             text NOT NULL DEFAULT '',
  body              text NOT NULL DEFAULT '',
  -- 'note' (typed) | 'pdf' (extracted). Kept as text, not an enum, so a new source needs
  -- no migration.
  source_kind       text NOT NULL DEFAULT 'note',
  -- Original filename for a PDF, so the UI can show what an entry came from.
  source_name       text,
  -- Where the uploaded document is readable, when the entry came from one.
  source_url        text,
  storage_key       text,
  -- 'active' entries are eligible for retrieval; 'disabled' are kept but never surfaced to
  -- the assistant, so an entry can be parked without deleting it.
  status            text NOT NULL DEFAULT 'active',
  tags              text[] NOT NULL DEFAULT '{}',
  -- Derived on write (title || ' ' || body). Never selected back; only fed to to_tsvector.
  search_text       text NOT NULL DEFAULT '',
  created_by_email  text,
  updated_by_email  text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS knowledge_entries_search_idx
  ON knowledge_entries USING gin (to_tsvector('english', search_text));
CREATE INDEX IF NOT EXISTS knowledge_entries_status_idx
  ON knowledge_entries (status, updated_at DESC);
CREATE INDEX IF NOT EXISTS knowledge_entries_recent_idx
  ON knowledge_entries (updated_at DESC);
`,
  },
  {
    id: 3,
    name: "seed_partner_logos",
    sql: /* sql */ `
-- Populate the homepage partners strip with the infrastructure providers, each with a
-- self-hosted brand logo (public/partners/*.svg). Before this, the strip's default content was
-- empty, so once the homepage was wired to the CMS it showed only whatever an administrator had
-- typed. This seeds the providers so the strip looks complete out of the box, while leaving any
-- partners the administrator already added in place — their entries are kept, the providers are
-- prepended. Guarded on the AWS entry so re-running (or an operator who already added AWS) is a
-- no-op rather than creating duplicates.
UPDATE site_sections
SET fields = jsonb_set(
  COALESCE(fields, '{}'::jsonb),
  '{items}',
  '[
    {"name":"Amazon Web Services","tagline":"Cloud Infrastructure","logo":"/partners/aws.svg","url":"https://aws.amazon.com"},
    {"name":"Google Cloud","tagline":"AI & Compute","logo":"/partners/googlecloud.svg","url":"https://cloud.google.com"},
    {"name":"Supabase","tagline":"Database & Auth","logo":"/partners/supabase.svg","url":"https://supabase.com"},
    {"name":"Vercel","tagline":"Edge Delivery","logo":"/partners/vercel.svg","url":"https://vercel.com"},
    {"name":"AWS Activate","tagline":"Startup Program","logo":"/partners/aws-activate.svg","url":"https://aws.amazon.com/activate/"},
    {"name":"Resend","tagline":"Transactional Email","logo":"/partners/resend.svg","url":"https://resend.com"}
  ]'::jsonb || COALESCE(fields->'items', '[]'::jsonb)
)
WHERE key = 'home.partners'
  AND NOT (COALESCE(fields->'items', '[]'::jsonb) @> '[{"name":"Amazon Web Services"}]'::jsonb);
`,
  },
  {
    id: 4,
    name: "repair_partners_section",
    sql: /* sql */ `
-- Repair the homepage partners strip so it is present, visible and populated regardless of the
-- state it was left in while editing. Migration 3 only updated an existing row's items; if the
-- row was missing or had been hidden/unpublished, the strip would still not appear once the
-- homepage reads it from the CMS. This upserts the section: it creates it if absent, forces it
-- back to visible + published, and ensures the infrastructure providers are present (prepended,
-- keeping any partners already added). Idempotent — providers are only added when absent.
INSERT INTO site_sections (key, label, group_name, type, visible, status, fields, sort_order)
VALUES (
  'home.partners', 'Partners strip', 'Home', 'logoStrip', true, 'published',
  '{"heading":"Working with","items":[
    {"name":"Amazon Web Services","tagline":"Cloud Infrastructure","logo":"/partners/aws.svg","url":"https://aws.amazon.com"},
    {"name":"Google Cloud","tagline":"AI & Compute","logo":"/partners/googlecloud.svg","url":"https://cloud.google.com"},
    {"name":"Supabase","tagline":"Database & Auth","logo":"/partners/supabase.svg","url":"https://supabase.com"},
    {"name":"Vercel","tagline":"Edge Delivery","logo":"/partners/vercel.svg","url":"https://vercel.com"},
    {"name":"AWS Activate","tagline":"Startup Program","logo":"/partners/aws-activate.svg","url":"https://aws.amazon.com/activate/"},
    {"name":"Resend","tagline":"Transactional Email","logo":"/partners/resend.svg","url":"https://resend.com"}
  ]}'::jsonb,
  40
)
ON CONFLICT (key) DO UPDATE SET
  visible = true,
  status = 'published',
  fields = jsonb_set(
    COALESCE(site_sections.fields, '{}'::jsonb),
    '{items}',
    CASE
      WHEN COALESCE(site_sections.fields->'items', '[]'::jsonb) @> '[{"name":"Amazon Web Services"}]'::jsonb
        THEN site_sections.fields->'items'
      ELSE '[
        {"name":"Amazon Web Services","tagline":"Cloud Infrastructure","logo":"/partners/aws.svg","url":"https://aws.amazon.com"},
        {"name":"Google Cloud","tagline":"AI & Compute","logo":"/partners/googlecloud.svg","url":"https://cloud.google.com"},
        {"name":"Supabase","tagline":"Database & Auth","logo":"/partners/supabase.svg","url":"https://supabase.com"},
        {"name":"Vercel","tagline":"Edge Delivery","logo":"/partners/vercel.svg","url":"https://vercel.com"},
        {"name":"AWS Activate","tagline":"Startup Program","logo":"/partners/aws-activate.svg","url":"https://aws.amazon.com/activate/"},
        {"name":"Resend","tagline":"Transactional Email","logo":"/partners/resend.svg","url":"https://resend.com"}
      ]'::jsonb || COALESCE(site_sections.fields->'items', '[]'::jsonb)
    END
  ),
  updated_at = now();
`,
  },
  {
    id: 5,
    name: "hero_current_copy",
    sql: /* sql */ `
-- The homepage hero is now rendered from this section. Set its content to the copy the site
-- already displays, so wiring it changes nothing visible. Only applied when the hero still holds
-- the original generic seed heading, so an operator who has edited it is left untouched. In the
-- heading, a newline splits the line and [[...]] marks the phrase shown in the accent colour.
UPDATE site_sections
SET fields = fields || '{
  "eyebrow": "Technology Group · Building for Africa",
  "heading": "We build the technology\\n[[behind Africa''s next]]\\ngeneration of\\nbusinesses.",
  "subheading": "ENICE Group builds, owns, and operates technology products for financial services, commerce, and business communication.",
  "primaryCtaLabel": "Explore our products",
  "primaryCtaUrl": "/portfolio",
  "secondaryCtaLabel": "What we build",
  "secondaryCtaUrl": "/about"
}'::jsonb,
    updated_at = now()
WHERE key = 'home.hero'
  AND fields->>'heading' = 'Technology products for financial services, commerce, and communication';
`,
  },
  {
    id: 6,
    name: "home_bands_current_copy",
    sql: /* sql */ `
-- The hero's statistics strip and the product band's heading are now rendered from these
-- sections, so set them to the copy the site already displays — wiring them changes nothing
-- visible. Each is guarded on its original seed value, so a band an operator has already edited
-- is left alone.
UPDATE site_sections
SET fields = fields || '{
  "heading": "Built for scale",
  "items": [
    {"value":"4","label":"Products in Ecosystem"},
    {"value":"99.99%","label":"Infrastructure SLA"},
    {"value":"< 14ms","label":"API Latency P50"},
    {"value":"AES-256","label":"Encryption Standard"}
  ]
}'::jsonb,
    updated_at = now()
WHERE key = 'home.statistics'
  AND fields->'items' @> '[{"label":"Products in the portfolio"}]'::jsonb;

UPDATE site_sections
SET fields = fields || '{
  "eyebrow": "What we''re building",
  "heading": "Products and platforms.\\nBuilt to one standard.",
  "subheading": "ENICE Group takes hard problems in financial services and business communication and turns them into products people can rely on."
}'::jsonb,
    updated_at = now()
WHERE key = 'home.products'
  AND fields->>'heading' = 'What we build';
`,
  },
  {
    id: 7,
    name: "home_product_cards",
    sql: /* sql */ `
-- The homepage product band renders its cards from this section's items. Its seeded items were a
-- five-entry product list that the homepage never rendered, so set them to the three cards the
-- band actually shows — wiring the cards changes nothing visible, and they become editable.
-- Guarded on the original seed (the PulsePay entry), so a list an operator has already edited is
-- left untouched. Bullets are newline-separated in one field; card numbering is positional.
UPDATE site_sections
SET fields = jsonb_set(fields, '{items}', '[
  {
    "icon": "Banknote",
    "kicker": "Fintech",
    "title": "Financial Infrastructure Systems",
    "description": "Transaction networks, ledger databases, and virtual card infrastructure built for Nigeria''s digital economy, with room to expand across the region.",
    "bullets": "Virtual Card Issuance\\nTreasury and Ledger\\nKYC and Compliance Tooling"
  },
  {
    "icon": "BrainCircuit",
    "kicker": "Artificial Intelligence",
    "title": "Autonomous Enterprise AI",
    "description": "Conversational AI that handles customer support, compliance monitoring, and daily operations for banks, fintechs, and telecoms.",
    "bullets": "Autonomous Customer Support\\nPolicy-Bound AI Agents\\nWorkflow Automation"
  },
  {
    "icon": "Boxes",
    "kicker": "Product Engineering",
    "title": "Products built to operate",
    "description": "We build, own, and operate full-stack products. Each platform starts from a real customer problem and goes through engineering, launch, and day-to-day operation.",
    "bullets": "Product Ownership\\nPlatform Engineering\\nContinuous Operation"
  }
]'::jsonb),
    updated_at = now()
WHERE key = 'home.products'
  AND fields->'items' @> '[{"title":"PulsePay"}]'::jsonb;
`,
  },
];

/** Bookkeeping table, created before any migration runs. */
export const MIGRATIONS_TABLE_SQL = /* sql */ `
CREATE TABLE IF NOT EXISTS cms_migrations (
  id         integer PRIMARY KEY,
  name       text NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now()
);
`;

/**
 * A 64-bit key for `pg_advisory_lock`, held while migrating.
 *
 * Several serverless instances can cold-start simultaneously and all decide to migrate.
 * `IF NOT EXISTS` makes the statements individually safe, but concurrent `CREATE INDEX` on the
 * same relation can still deadlock, so the whole run is serialised behind this lock. The value
 * is an arbitrary constant — only its uniqueness within the database matters. It is a string
 * because postgres.js will not bind a JavaScript bigint; the SQL casts it back.
 */
export const MIGRATION_LOCK_KEY = "8324119407551002";
