/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutPulseassistBetaRouteImport } from './routes/about-pulseassist-beta'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminKnowledgeRouteImport } from './routes/admin/knowledge'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements.index'
import { Route as AnnouncementsSlugRouteImport } from './routes/announcements.$slug'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioDevapayRouteImport } from './routes/portfolio.devapay'
import { Route as PortfolioPrideRouteImport } from './routes/portfolio.pride'
import { Route as PortfolioPulseassistRouteImport } from './routes/portfolio.pulseassist'
import { Route as PortfolioPulseassistEmailRouteImport } from './routes/portfolio.pulseassist-email'
import { Route as PortfolioPulsepayRouteImport } from './routes/portfolio.pulsepay'
import { Route as AdminAdministrationSettingsRouteImport } from './routes/admin/administration.settings'
import { Route as AdminContentKindIndexRouteImport } from './routes/admin/content.$kind.index'
import { Route as AdminContentKindItemIdRouteImport } from './routes/admin/content.$kind.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPulseassistBetaRoute = AboutPulseassistBetaRouteImport.update({
  id: '/about-pulseassist-beta',
  path: '/about-pulseassist-beta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsSlugRoute = AnnouncementsSlugRouteImport.update({
  id: '/announcements/$slug',
  path: '/announcements/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioDevapayRoute = PortfolioDevapayRouteImport.update({
  id: '/devapay',
  path: '/devapay',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioPrideRoute = PortfolioPrideRouteImport.update({
  id: '/pride',
  path: '/pride',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioPulseassistRoute = PortfolioPulseassistRouteImport.update({
  id: '/pulseassist',
  path: '/pulseassist',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioPulseassistEmailRoute =
  PortfolioPulseassistEmailRouteImport.update({
    id: '/pulseassist-email',
    path: '/pulseassist-email',
    getParentRoute: () => PortfolioRoute,
  } as any)
const PortfolioPulsepayRoute = PortfolioPulsepayRouteImport.update({
  id: '/pulsepay',
  path: '/pulsepay',
  getParentRoute: () => PortfolioRoute,
} as any)
const AdminAdministrationSettingsRoute =
  AdminAdministrationSettingsRouteImport.update({
    id: '/administration/settings',
    path: '/administration/settings',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContentKindIndexRoute = AdminContentKindIndexRouteImport.update({
  id: '/content/$kind/',
  path: '/content/$kind/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentKindItemIdRoute = AdminContentKindItemIdRouteImport.update({
  id: '/content/$kind/$itemId',
  path: '/content/$kind/$itemId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/about-pulseassist-beta': typeof AboutPulseassistBetaRoute
  '/admin': typeof AdminRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/portfolio/devapay': typeof PortfolioDevapayRoute
  '/portfolio/pride': typeof PortfolioPrideRoute
  '/portfolio/pulseassist': typeof PortfolioPulseassistRoute
  '/portfolio/pulseassist-email': typeof PortfolioPulseassistEmailRoute
  '/portfolio/pulsepay': typeof PortfolioPulsepayRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/news/': typeof NewsIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/admin/administration/settings': typeof AdminAdministrationSettingsRoute
  '/admin/content/$kind/$itemId': typeof AdminContentKindItemIdRoute
  '/admin/content/$kind/': typeof AdminContentKindIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/about-pulseassist-beta': typeof AboutPulseassistBetaRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/portfolio/devapay': typeof PortfolioDevapayRoute
  '/portfolio/pride': typeof PortfolioPrideRoute
  '/portfolio/pulseassist': typeof PortfolioPulseassistRoute
  '/portfolio/pulseassist-email': typeof PortfolioPulseassistEmailRoute
  '/portfolio/pulsepay': typeof PortfolioPulsepayRoute
  '/admin': typeof AdminIndexRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/news': typeof NewsIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/admin/administration/settings': typeof AdminAdministrationSettingsRoute
  '/admin/content/$kind/$itemId': typeof AdminContentKindItemIdRoute
  '/admin/content/$kind': typeof AdminContentKindIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/about-pulseassist-beta': typeof AboutPulseassistBetaRoute
  '/admin': typeof AdminRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/portfolio/devapay': typeof PortfolioDevapayRoute
  '/portfolio/pride': typeof PortfolioPrideRoute
  '/portfolio/pulseassist': typeof PortfolioPulseassistRoute
  '/portfolio/pulseassist-email': typeof PortfolioPulseassistEmailRoute
  '/portfolio/pulsepay': typeof PortfolioPulsepayRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/news/': typeof NewsIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/admin/administration/settings': typeof AdminAdministrationSettingsRoute
  '/admin/content/$kind/$itemId': typeof AdminContentKindItemIdRoute
  '/admin/content/$kind/': typeof AdminContentKindIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/about-pulseassist-beta'
    | '/admin'
    | '/compliance'
    | '/contact'
    | '/docs'
    | '/portfolio'
    | '/privacy'
    | '/roadmap'
    | '/status'
    | '/terms'
    | '/admin/knowledge'
    | '/announcements/$slug'
    | '/blog/$slug'
    | '/news/$slug'
    | '/portfolio/devapay'
    | '/portfolio/pride'
    | '/portfolio/pulseassist'
    | '/portfolio/pulseassist-email'
    | '/portfolio/pulsepay'
    | '/admin/'
    | '/announcements/'
    | '/blog/'
    | '/news/'
    | '/portfolio/'
    | '/admin/administration/settings'
    | '/admin/content/$kind/$itemId'
    | '/admin/content/$kind/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/about-pulseassist-beta'
    | '/compliance'
    | '/contact'
    | '/docs'
    | '/privacy'
    | '/roadmap'
    | '/status'
    | '/terms'
    | '/admin/knowledge'
    | '/announcements/$slug'
    | '/blog/$slug'
    | '/news/$slug'
    | '/portfolio/devapay'
    | '/portfolio/pride'
    | '/portfolio/pulseassist'
    | '/portfolio/pulseassist-email'
    | '/portfolio/pulsepay'
    | '/admin'
    | '/announcements'
    | '/blog'
    | '/news'
    | '/portfolio'
    | '/admin/administration/settings'
    | '/admin/content/$kind/$itemId'
    | '/admin/content/$kind'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/about-pulseassist-beta'
    | '/admin'
    | '/compliance'
    | '/contact'
    | '/docs'
    | '/portfolio'
    | '/privacy'
    | '/roadmap'
    | '/status'
    | '/terms'
    | '/admin/knowledge'
    | '/announcements/$slug'
    | '/blog/$slug'
    | '/news/$slug'
    | '/portfolio/devapay'
    | '/portfolio/pride'
    | '/portfolio/pulseassist'
    | '/portfolio/pulseassist-email'
    | '/portfolio/pulsepay'
    | '/admin/'
    | '/announcements/'
    | '/blog/'
    | '/news/'
    | '/portfolio/'
    | '/admin/administration/settings'
    | '/admin/content/$kind/$itemId'
    | '/admin/content/$kind/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AboutPulseassistBetaRoute: typeof AboutPulseassistBetaRoute
  AdminRoute: typeof AdminRouteWithChildren
  ComplianceRoute: typeof ComplianceRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RoadmapRoute: typeof RoadmapRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  AnnouncementsSlugRoute: typeof AnnouncementsSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-pulseassist-beta': {
      id: '/about-pulseassist-beta'
      path: '/about-pulseassist-beta'
      fullPath: '/about-pulseassist-beta'
      preLoaderRoute: typeof AboutPulseassistBetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/$slug': {
      id: '/announcements/$slug'
      path: '/announcements/$slug'
      fullPath: '/announcements/$slug'
      preLoaderRoute: typeof AnnouncementsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/devapay': {
      id: '/portfolio/devapay'
      path: '/devapay'
      fullPath: '/portfolio/devapay'
      preLoaderRoute: typeof PortfolioDevapayRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/pride': {
      id: '/portfolio/pride'
      path: '/pride'
      fullPath: '/portfolio/pride'
      preLoaderRoute: typeof PortfolioPrideRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/pulseassist': {
      id: '/portfolio/pulseassist'
      path: '/pulseassist'
      fullPath: '/portfolio/pulseassist'
      preLoaderRoute: typeof PortfolioPulseassistRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/pulseassist-email': {
      id: '/portfolio/pulseassist-email'
      path: '/pulseassist-email'
      fullPath: '/portfolio/pulseassist-email'
      preLoaderRoute: typeof PortfolioPulseassistEmailRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/pulsepay': {
      id: '/portfolio/pulsepay'
      path: '/pulsepay'
      fullPath: '/portfolio/pulsepay'
      preLoaderRoute: typeof PortfolioPulsepayRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/admin/administration/settings': {
      id: '/admin/administration/settings'
      path: '/administration/settings'
      fullPath: '/admin/administration/settings'
      preLoaderRoute: typeof AdminAdministrationSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/$kind/': {
      id: '/admin/content/$kind/'
      path: '/content/$kind'
      fullPath: '/admin/content/$kind/'
      preLoaderRoute: typeof AdminContentKindIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/$kind/$itemId': {
      id: '/admin/content/$kind/$itemId'
      path: '/content/$kind/$itemId'
      fullPath: '/admin/content/$kind/$itemId'
      preLoaderRoute: typeof AdminContentKindItemIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdministrationSettingsRoute: typeof AdminAdministrationSettingsRoute
  AdminContentKindItemIdRoute: typeof AdminContentKindItemIdRoute
  AdminContentKindIndexRoute: typeof AdminContentKindIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAdministrationSettingsRoute: AdminAdministrationSettingsRoute,
  AdminContentKindItemIdRoute: AdminContentKindItemIdRoute,
  AdminContentKindIndexRoute: AdminContentKindIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortfolioRouteChildren {
  PortfolioDevapayRoute: typeof PortfolioDevapayRoute
  PortfolioPrideRoute: typeof PortfolioPrideRoute
  PortfolioPulseassistRoute: typeof PortfolioPulseassistRoute
  PortfolioPulseassistEmailRoute: typeof PortfolioPulseassistEmailRoute
  PortfolioPulsepayRoute: typeof PortfolioPulsepayRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioDevapayRoute: PortfolioDevapayRoute,
  PortfolioPrideRoute: PortfolioPrideRoute,
  PortfolioPulseassistRoute: PortfolioPulseassistRoute,
  PortfolioPulseassistEmailRoute: PortfolioPulseassistEmailRoute,
  PortfolioPulsepayRoute: PortfolioPulsepayRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AboutPulseassistBetaRoute: AboutPulseassistBetaRoute,
  AdminRoute: AdminRouteWithChildren,
  ComplianceRoute: ComplianceRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RoadmapRoute: RoadmapRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  AnnouncementsSlugRoute: AnnouncementsSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
