/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutPulseassistBetaRouteImport } from './routes/about-pulseassist-beta'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAiRouteImport } from './routes/admin/ai'
import { Route as AdminEarlyAccessRouteImport } from './routes/admin/early-access'
import { Route as AdminInviteRouteImport } from './routes/admin/invite'
import { Route as AdminKnowledgeRouteImport } from './routes/admin/knowledge'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements.index'
import { Route as AnnouncementsSlugRouteImport } from './routes/announcements.$slug'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioEpulseRouteImport } from './routes/portfolio.epulse'
import { Route as PortfolioPaymentCollectionRouteImport } from './routes/portfolio.payment-collection'
import { Route as PortfolioPulseassistRouteImport } from './routes/portfolio.pulseassist'
import { Route as PortfolioPulsepayRouteImport } from './routes/portfolio.pulsepay'
import { Route as PortfolioPulsexRouteImport } from './routes/portfolio.pulsex'
import { Route as AdminAdministrationActivityRouteImport } from './routes/admin/administration.activity'
import { Route as AdminAdministrationAdminsRouteImport } from './routes/admin/administration.admins'
import { Route as AdminAdministrationRolesRouteImport } from './routes/admin/administration.roles'
import { Route as AdminAdministrationSettingsRouteImport } from './routes/admin/administration.settings'
import { Route as AdminPublishingArchivedRouteImport } from './routes/admin/publishing.archived'
import { Route as AdminPublishingDraftsRouteImport } from './routes/admin/publishing.drafts'
import { Route as AdminPublishingPublishedRouteImport } from './routes/admin/publishing.published'
import { Route as AdminPublishingScheduledRouteImport } from './routes/admin/publishing.scheduled'
import { Route as AdminWebsiteDesignRouteImport } from './routes/admin/website.design'
import { Route as AdminWebsiteFooterRouteImport } from './routes/admin/website.footer'
import { Route as AdminWebsiteNavigationRouteImport } from './routes/admin/website.navigation'
import { Route as AdminWebsiteSectionsRouteImport } from './routes/admin/website.sections'
import { Route as AdminWebsiteSeoRouteImport } from './routes/admin/website.seo'
import { Route as AdminContentKindIndexRouteImport } from './routes/admin/content.$kind.index'
import { Route as AdminContentKindItemIdRouteImport } from './routes/admin/content.$kind.$itemId'
import { Route as AdminWebsitePagesIndexRouteImport } from './routes/admin/website.pages.index'
import { Route as AdminWebsitePagesPageIdRouteImport } from './routes/admin/website.pages.$pageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPulseassistBetaRoute = AboutPulseassistBetaRouteImport.update({
  id: '/about-pulseassist-beta',
  path: '/about-pulseassist-beta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEarlyAccessRoute = AdminEarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInviteRoute = AdminInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsSlugRoute = AnnouncementsSlugRouteImport.update({
  id: '/announcements/$slug',
  path: '/announcements/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioEpulseRoute = PortfolioEpulseRouteImport.update({
  id: '/epulse',
  path: '/epulse',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioPaymentCollectionRoute =
  PortfolioPaymentCollectionRouteImport.update({
    id: '/payment-collection',
    path: '/payment-collection',
    getParentRoute: () => PortfolioRoute,
  } as any)
const PortfolioPulseassistRoute = PortfolioPulseassistRouteImport.update({
  id: '/pulseassist',
  path: '/pulseassist',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioPulsepayRoute = PortfolioPulsepayRouteImport.update({
  id: '/pulsepay',
  path: '/pulsepay',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioPulsexRoute = PortfolioPulsexRouteImport.update({
  id: '/pulsex',
  path: '/pulsex',
  getParentRoute: () => PortfolioRoute,
} as any)
const AdminAdministrationActivityRoute =
  AdminAdministrationActivityRouteImport.update({
    id: '/administration/activity',
    path: '/administration/activity',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdministrationAdminsRoute =
  AdminAdministrationAdminsRouteImport.update({
    id: '/administration/admins',
    path: '/administration/admins',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdministrationRolesRoute =
  AdminAdministrationRolesRouteImport.update({
    id: '/administration/roles',
    path: '/administration/roles',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdministrationSettingsRoute =
  AdminAdministrationSettingsRouteImport.update({
    id: '/administration/settings',
    path: '/administration/settings',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPublishingArchivedRoute = AdminPublishingArchivedRouteImport.update({
  id: '/publishing/archived',
  path: '/publishing/archived',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublishingDraftsRoute = AdminPublishingDraftsRouteImport.update({
  id: '/publishing/drafts',
  path: '/publishing/drafts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublishingPublishedRoute =
  AdminPublishingPublishedRouteImport.update({
    id: '/publishing/published',
    path: '/publishing/published',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPublishingScheduledRoute =
  AdminPublishingScheduledRouteImport.update({
    id: '/publishing/scheduled',
    path: '/publishing/scheduled',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminWebsiteDesignRoute = AdminWebsiteDesignRouteImport.update({
  id: '/website/design',
  path: '/website/design',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteFooterRoute = AdminWebsiteFooterRouteImport.update({
  id: '/website/footer',
  path: '/website/footer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteNavigationRoute = AdminWebsiteNavigationRouteImport.update({
  id: '/website/navigation',
  path: '/website/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteSectionsRoute = AdminWebsiteSectionsRouteImport.update({
  id: '/website/sections',
  path: '/website/sections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteSeoRoute = AdminWebsiteSeoRouteImport.update({
  id: '/website/seo',
  path: '/website/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentKindIndexRoute = AdminContentKindIndexRouteImport.update({
  id: '/content/$kind/',
  path: '/content/$kind/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentKindItemIdRoute = AdminContentKindItemIdRouteImport.update({
  id: '/content/$kind/$itemId',
  path: '/content/$kind/$itemId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsitePagesIndexRoute = AdminWebsitePagesIndexRouteImport.update({
  id: '/website/pages/',
  path: '/website/pages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsitePagesPageIdRoute = AdminWebsitePagesPageIdRouteImport.update({
  id: '/website/pages/$pageId',
  path: '/website/pages/$pageId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/about-pulseassist-beta': typeof AboutPulseassistBetaRoute
  '/admin': typeof AdminRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/early-access': typeof AdminEarlyAccessRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/media': typeof AdminMediaRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/portfolio/epulse': typeof PortfolioEpulseRoute
  '/portfolio/payment-collection': typeof PortfolioPaymentCollectionRoute
  '/portfolio/pulseassist': typeof PortfolioPulseassistRoute
  '/portfolio/pulsepay': typeof PortfolioPulsepayRoute
  '/portfolio/pulsex': typeof PortfolioPulsexRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/news/': typeof NewsIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/admin/administration/activity': typeof AdminAdministrationActivityRoute
  '/admin/administration/admins': typeof AdminAdministrationAdminsRoute
  '/admin/administration/roles': typeof AdminAdministrationRolesRoute
  '/admin/administration/settings': typeof AdminAdministrationSettingsRoute
  '/admin/publishing/archived': typeof AdminPublishingArchivedRoute
  '/admin/publishing/drafts': typeof AdminPublishingDraftsRoute
  '/admin/publishing/published': typeof AdminPublishingPublishedRoute
  '/admin/publishing/scheduled': typeof AdminPublishingScheduledRoute
  '/admin/website/design': typeof AdminWebsiteDesignRoute
  '/admin/website/footer': typeof AdminWebsiteFooterRoute
  '/admin/website/navigation': typeof AdminWebsiteNavigationRoute
  '/admin/website/sections': typeof AdminWebsiteSectionsRoute
  '/admin/website/seo': typeof AdminWebsiteSeoRoute
  '/admin/content/$kind/$itemId': typeof AdminContentKindItemIdRoute
  '/admin/website/pages/$pageId': typeof AdminWebsitePagesPageIdRoute
  '/admin/content/$kind/': typeof AdminContentKindIndexRoute
  '/admin/website/pages/': typeof AdminWebsitePagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/about-pulseassist-beta': typeof AboutPulseassistBetaRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/early-access': typeof AdminEarlyAccessRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/media': typeof AdminMediaRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/portfolio/epulse': typeof PortfolioEpulseRoute
  '/portfolio/payment-collection': typeof PortfolioPaymentCollectionRoute
  '/portfolio/pulseassist': typeof PortfolioPulseassistRoute
  '/portfolio/pulsepay': typeof PortfolioPulsepayRoute
  '/portfolio/pulsex': typeof PortfolioPulsexRoute
  '/admin': typeof AdminIndexRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/news': typeof NewsIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/admin/administration/activity': typeof AdminAdministrationActivityRoute
  '/admin/administration/admins': typeof AdminAdministrationAdminsRoute
  '/admin/administration/roles': typeof AdminAdministrationRolesRoute
  '/admin/administration/settings': typeof AdminAdministrationSettingsRoute
  '/admin/publishing/archived': typeof AdminPublishingArchivedRoute
  '/admin/publishing/drafts': typeof AdminPublishingDraftsRoute
  '/admin/publishing/published': typeof AdminPublishingPublishedRoute
  '/admin/publishing/scheduled': typeof AdminPublishingScheduledRoute
  '/admin/website/design': typeof AdminWebsiteDesignRoute
  '/admin/website/footer': typeof AdminWebsiteFooterRoute
  '/admin/website/navigation': typeof AdminWebsiteNavigationRoute
  '/admin/website/sections': typeof AdminWebsiteSectionsRoute
  '/admin/website/seo': typeof AdminWebsiteSeoRoute
  '/admin/content/$kind/$itemId': typeof AdminContentKindItemIdRoute
  '/admin/website/pages/$pageId': typeof AdminWebsitePagesPageIdRoute
  '/admin/content/$kind': typeof AdminContentKindIndexRoute
  '/admin/website/pages': typeof AdminWebsitePagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/about-pulseassist-beta': typeof AboutPulseassistBetaRoute
  '/admin': typeof AdminRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/early-access': typeof AdminEarlyAccessRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/media': typeof AdminMediaRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/portfolio/epulse': typeof PortfolioEpulseRoute
  '/portfolio/payment-collection': typeof PortfolioPaymentCollectionRoute
  '/portfolio/pulseassist': typeof PortfolioPulseassistRoute
  '/portfolio/pulsepay': typeof PortfolioPulsepayRoute
  '/portfolio/pulsex': typeof PortfolioPulsexRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/news/': typeof NewsIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/admin/administration/activity': typeof AdminAdministrationActivityRoute
  '/admin/administration/admins': typeof AdminAdministrationAdminsRoute
  '/admin/administration/roles': typeof AdminAdministrationRolesRoute
  '/admin/administration/settings': typeof AdminAdministrationSettingsRoute
  '/admin/publishing/archived': typeof AdminPublishingArchivedRoute
  '/admin/publishing/drafts': typeof AdminPublishingDraftsRoute
  '/admin/publishing/published': typeof AdminPublishingPublishedRoute
  '/admin/publishing/scheduled': typeof AdminPublishingScheduledRoute
  '/admin/website/design': typeof AdminWebsiteDesignRoute
  '/admin/website/footer': typeof AdminWebsiteFooterRoute
  '/admin/website/navigation': typeof AdminWebsiteNavigationRoute
  '/admin/website/sections': typeof AdminWebsiteSectionsRoute
  '/admin/website/seo': typeof AdminWebsiteSeoRoute
  '/admin/content/$kind/$itemId': typeof AdminContentKindItemIdRoute
  '/admin/website/pages/$pageId': typeof AdminWebsitePagesPageIdRoute
  '/admin/content/$kind/': typeof AdminContentKindIndexRoute
  '/admin/website/pages/': typeof AdminWebsitePagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/about-pulseassist-beta'
    | '/admin'
    | '/compliance'
    | '/contact'
    | '/docs'
    | '/portfolio'
    | '/privacy'
    | '/roadmap'
    | '/status'
    | '/terms'
    | '/admin/ai'
    | '/admin/early-access'
    | '/admin/invite'
    | '/admin/knowledge'
    | '/admin/media'
    | '/announcements/$slug'
    | '/blog/$slug'
    | '/news/$slug'
    | '/portfolio/epulse'
    | '/portfolio/payment-collection'
    | '/portfolio/pulseassist'
    | '/portfolio/pulsepay'
    | '/portfolio/pulsex'
    | '/admin/'
    | '/announcements/'
    | '/blog/'
    | '/news/'
    | '/portfolio/'
    | '/admin/administration/activity'
    | '/admin/administration/admins'
    | '/admin/administration/roles'
    | '/admin/administration/settings'
    | '/admin/publishing/archived'
    | '/admin/publishing/drafts'
    | '/admin/publishing/published'
    | '/admin/publishing/scheduled'
    | '/admin/website/design'
    | '/admin/website/footer'
    | '/admin/website/navigation'
    | '/admin/website/sections'
    | '/admin/website/seo'
    | '/admin/content/$kind/$itemId'
    | '/admin/website/pages/$pageId'
    | '/admin/content/$kind/'
    | '/admin/website/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/about-pulseassist-beta'
    | '/compliance'
    | '/contact'
    | '/docs'
    | '/privacy'
    | '/roadmap'
    | '/status'
    | '/terms'
    | '/admin/ai'
    | '/admin/early-access'
    | '/admin/invite'
    | '/admin/knowledge'
    | '/admin/media'
    | '/announcements/$slug'
    | '/blog/$slug'
    | '/news/$slug'
    | '/portfolio/epulse'
    | '/portfolio/payment-collection'
    | '/portfolio/pulseassist'
    | '/portfolio/pulsepay'
    | '/portfolio/pulsex'
    | '/admin'
    | '/announcements'
    | '/blog'
    | '/news'
    | '/portfolio'
    | '/admin/administration/activity'
    | '/admin/administration/admins'
    | '/admin/administration/roles'
    | '/admin/administration/settings'
    | '/admin/publishing/archived'
    | '/admin/publishing/drafts'
    | '/admin/publishing/published'
    | '/admin/publishing/scheduled'
    | '/admin/website/design'
    | '/admin/website/footer'
    | '/admin/website/navigation'
    | '/admin/website/sections'
    | '/admin/website/seo'
    | '/admin/content/$kind/$itemId'
    | '/admin/website/pages/$pageId'
    | '/admin/content/$kind'
    | '/admin/website/pages'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/about-pulseassist-beta'
    | '/admin'
    | '/compliance'
    | '/contact'
    | '/docs'
    | '/portfolio'
    | '/privacy'
    | '/roadmap'
    | '/status'
    | '/terms'
    | '/admin/ai'
    | '/admin/early-access'
    | '/admin/invite'
    | '/admin/knowledge'
    | '/admin/media'
    | '/announcements/$slug'
    | '/blog/$slug'
    | '/news/$slug'
    | '/portfolio/epulse'
    | '/portfolio/payment-collection'
    | '/portfolio/pulseassist'
    | '/portfolio/pulsepay'
    | '/portfolio/pulsex'
    | '/admin/'
    | '/announcements/'
    | '/blog/'
    | '/news/'
    | '/portfolio/'
    | '/admin/administration/activity'
    | '/admin/administration/admins'
    | '/admin/administration/roles'
    | '/admin/administration/settings'
    | '/admin/publishing/archived'
    | '/admin/publishing/drafts'
    | '/admin/publishing/published'
    | '/admin/publishing/scheduled'
    | '/admin/website/design'
    | '/admin/website/footer'
    | '/admin/website/navigation'
    | '/admin/website/sections'
    | '/admin/website/seo'
    | '/admin/content/$kind/$itemId'
    | '/admin/website/pages/$pageId'
    | '/admin/content/$kind/'
    | '/admin/website/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AboutPulseassistBetaRoute: typeof AboutPulseassistBetaRoute
  AdminRoute: typeof AdminRouteWithChildren
  ComplianceRoute: typeof ComplianceRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RoadmapRoute: typeof RoadmapRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  AnnouncementsSlugRoute: typeof AnnouncementsSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-pulseassist-beta': {
      id: '/about-pulseassist-beta'
      path: '/about-pulseassist-beta'
      fullPath: '/about-pulseassist-beta'
      preLoaderRoute: typeof AboutPulseassistBetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/early-access': {
      id: '/admin/early-access'
      path: '/early-access'
      fullPath: '/admin/early-access'
      preLoaderRoute: typeof AdminEarlyAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invite': {
      id: '/admin/invite'
      path: '/invite'
      fullPath: '/admin/invite'
      preLoaderRoute: typeof AdminInviteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/$slug': {
      id: '/announcements/$slug'
      path: '/announcements/$slug'
      fullPath: '/announcements/$slug'
      preLoaderRoute: typeof AnnouncementsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/epulse': {
      id: '/portfolio/epulse'
      path: '/epulse'
      fullPath: '/portfolio/epulse'
      preLoaderRoute: typeof PortfolioEpulseRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/payment-collection': {
      id: '/portfolio/payment-collection'
      path: '/payment-collection'
      fullPath: '/portfolio/payment-collection'
      preLoaderRoute: typeof PortfolioPaymentCollectionRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/pulseassist': {
      id: '/portfolio/pulseassist'
      path: '/pulseassist'
      fullPath: '/portfolio/pulseassist'
      preLoaderRoute: typeof PortfolioPulseassistRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/pulsepay': {
      id: '/portfolio/pulsepay'
      path: '/pulsepay'
      fullPath: '/portfolio/pulsepay'
      preLoaderRoute: typeof PortfolioPulsepayRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/pulsex': {
      id: '/portfolio/pulsex'
      path: '/pulsex'
      fullPath: '/portfolio/pulsex'
      preLoaderRoute: typeof PortfolioPulsexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/admin/administration/activity': {
      id: '/admin/administration/activity'
      path: '/administration/activity'
      fullPath: '/admin/administration/activity'
      preLoaderRoute: typeof AdminAdministrationActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administration/admins': {
      id: '/admin/administration/admins'
      path: '/administration/admins'
      fullPath: '/admin/administration/admins'
      preLoaderRoute: typeof AdminAdministrationAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administration/roles': {
      id: '/admin/administration/roles'
      path: '/administration/roles'
      fullPath: '/admin/administration/roles'
      preLoaderRoute: typeof AdminAdministrationRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administration/settings': {
      id: '/admin/administration/settings'
      path: '/administration/settings'
      fullPath: '/admin/administration/settings'
      preLoaderRoute: typeof AdminAdministrationSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/publishing/archived': {
      id: '/admin/publishing/archived'
      path: '/publishing/archived'
      fullPath: '/admin/publishing/archived'
      preLoaderRoute: typeof AdminPublishingArchivedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/publishing/drafts': {
      id: '/admin/publishing/drafts'
      path: '/publishing/drafts'
      fullPath: '/admin/publishing/drafts'
      preLoaderRoute: typeof AdminPublishingDraftsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/publishing/published': {
      id: '/admin/publishing/published'
      path: '/publishing/published'
      fullPath: '/admin/publishing/published'
      preLoaderRoute: typeof AdminPublishingPublishedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/publishing/scheduled': {
      id: '/admin/publishing/scheduled'
      path: '/publishing/scheduled'
      fullPath: '/admin/publishing/scheduled'
      preLoaderRoute: typeof AdminPublishingScheduledRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/design': {
      id: '/admin/website/design'
      path: '/website/design'
      fullPath: '/admin/website/design'
      preLoaderRoute: typeof AdminWebsiteDesignRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/footer': {
      id: '/admin/website/footer'
      path: '/website/footer'
      fullPath: '/admin/website/footer'
      preLoaderRoute: typeof AdminWebsiteFooterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/navigation': {
      id: '/admin/website/navigation'
      path: '/website/navigation'
      fullPath: '/admin/website/navigation'
      preLoaderRoute: typeof AdminWebsiteNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/sections': {
      id: '/admin/website/sections'
      path: '/website/sections'
      fullPath: '/admin/website/sections'
      preLoaderRoute: typeof AdminWebsiteSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/seo': {
      id: '/admin/website/seo'
      path: '/website/seo'
      fullPath: '/admin/website/seo'
      preLoaderRoute: typeof AdminWebsiteSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/$kind/': {
      id: '/admin/content/$kind/'
      path: '/content/$kind'
      fullPath: '/admin/content/$kind/'
      preLoaderRoute: typeof AdminContentKindIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/$kind/$itemId': {
      id: '/admin/content/$kind/$itemId'
      path: '/content/$kind/$itemId'
      fullPath: '/admin/content/$kind/$itemId'
      preLoaderRoute: typeof AdminContentKindItemIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/pages/': {
      id: '/admin/website/pages/'
      path: '/website/pages'
      fullPath: '/admin/website/pages/'
      preLoaderRoute: typeof AdminWebsitePagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/pages/$pageId': {
      id: '/admin/website/pages/$pageId'
      path: '/website/pages/$pageId'
      fullPath: '/admin/website/pages/$pageId'
      preLoaderRoute: typeof AdminWebsitePagesPageIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminEarlyAccessRoute: typeof AdminEarlyAccessRoute
  AdminInviteRoute: typeof AdminInviteRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdministrationActivityRoute: typeof AdminAdministrationActivityRoute
  AdminAdministrationAdminsRoute: typeof AdminAdministrationAdminsRoute
  AdminAdministrationRolesRoute: typeof AdminAdministrationRolesRoute
  AdminAdministrationSettingsRoute: typeof AdminAdministrationSettingsRoute
  AdminPublishingArchivedRoute: typeof AdminPublishingArchivedRoute
  AdminPublishingDraftsRoute: typeof AdminPublishingDraftsRoute
  AdminPublishingPublishedRoute: typeof AdminPublishingPublishedRoute
  AdminPublishingScheduledRoute: typeof AdminPublishingScheduledRoute
  AdminWebsiteDesignRoute: typeof AdminWebsiteDesignRoute
  AdminWebsiteFooterRoute: typeof AdminWebsiteFooterRoute
  AdminWebsiteNavigationRoute: typeof AdminWebsiteNavigationRoute
  AdminWebsiteSectionsRoute: typeof AdminWebsiteSectionsRoute
  AdminWebsiteSeoRoute: typeof AdminWebsiteSeoRoute
  AdminContentKindItemIdRoute: typeof AdminContentKindItemIdRoute
  AdminWebsitePagesPageIdRoute: typeof AdminWebsitePagesPageIdRoute
  AdminContentKindIndexRoute: typeof AdminContentKindIndexRoute
  AdminWebsitePagesIndexRoute: typeof AdminWebsitePagesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminEarlyAccessRoute: AdminEarlyAccessRoute,
  AdminInviteRoute: AdminInviteRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAdministrationActivityRoute: AdminAdministrationActivityRoute,
  AdminAdministrationAdminsRoute: AdminAdministrationAdminsRoute,
  AdminAdministrationRolesRoute: AdminAdministrationRolesRoute,
  AdminAdministrationSettingsRoute: AdminAdministrationSettingsRoute,
  AdminPublishingArchivedRoute: AdminPublishingArchivedRoute,
  AdminPublishingDraftsRoute: AdminPublishingDraftsRoute,
  AdminPublishingPublishedRoute: AdminPublishingPublishedRoute,
  AdminPublishingScheduledRoute: AdminPublishingScheduledRoute,
  AdminWebsiteDesignRoute: AdminWebsiteDesignRoute,
  AdminWebsiteFooterRoute: AdminWebsiteFooterRoute,
  AdminWebsiteNavigationRoute: AdminWebsiteNavigationRoute,
  AdminWebsiteSectionsRoute: AdminWebsiteSectionsRoute,
  AdminWebsiteSeoRoute: AdminWebsiteSeoRoute,
  AdminContentKindItemIdRoute: AdminContentKindItemIdRoute,
  AdminWebsitePagesPageIdRoute: AdminWebsitePagesPageIdRoute,
  AdminContentKindIndexRoute: AdminContentKindIndexRoute,
  AdminWebsitePagesIndexRoute: AdminWebsitePagesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortfolioRouteChildren {
  PortfolioEpulseRoute: typeof PortfolioEpulseRoute
  PortfolioPaymentCollectionRoute: typeof PortfolioPaymentCollectionRoute
  PortfolioPulseassistRoute: typeof PortfolioPulseassistRoute
  PortfolioPulsepayRoute: typeof PortfolioPulsepayRoute
  PortfolioPulsexRoute: typeof PortfolioPulsexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioEpulseRoute: PortfolioEpulseRoute,
  PortfolioPaymentCollectionRoute: PortfolioPaymentCollectionRoute,
  PortfolioPulseassistRoute: PortfolioPulseassistRoute,
  PortfolioPulsepayRoute: PortfolioPulsepayRoute,
  PortfolioPulsexRoute: PortfolioPulsexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AboutPulseassistBetaRoute: AboutPulseassistBetaRoute,
  AdminRoute: AdminRouteWithChildren,
  ComplianceRoute: ComplianceRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RoadmapRoute: RoadmapRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  AnnouncementsSlugRoute: AnnouncementsSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
